# Generated by Django 4.1.5 on 2023-02-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
