# Generated by Django 4.1.5 on 2023-02-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_cart_cart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_live',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
