# Generated by Django 4.1.5 on 2023-02-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_remove_bill_bill_data_bill_bill_pay_bill_bill_pro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='bill_quan',
            new_name='bill_amount',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='bill_pro',
            new_name='bill_data',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_pay',
            field=models.CharField(max_length=100),
        ),
    ]
